from tkinter import *
import tkinter as tk
import tkinter.messagebox
import tkinter.font as tkFont
import sqlite3

def fest1(p,i,i1,i2,i3):
    connection = sqlite3.connect('LES.db')
    cursor = connection.cursor()
    t=tk.Tk()
    t.title('LES CASE')
    bg = PhotoImage(file="wallpaper.png")
    label1 = Label(t, image=bg)
    label1.place(x=-10, y=-10)
    w, h = t.winfo_screenwidth(), t.winfo_screenheight()
    t.geometry("%dx%d+0+0" % (w, h))

    def back():
        t.destroy()
        from police_dashboard import police_dashboard
        police_dashboard(p)

    def update_case():
        cursor.execute("Update CASE1 set CASENO=? where CASENO=?", (case_id1.get(), i[0][0],))
        cursor.execute("Update CASE1 set SECTIONNUMBER =? where CASENO=?", (sn1.get(), i[0][0],))
        cursor.execute("Update CASE1 set POLICESTATION=? where CASENO=?", (ps1.get(), i[0][0],))
        cursor.execute("Update CASE1 set DESCRIPTION=? where CASENO=?", (desc1.get(), i[0][0],))
        cursor.execute("Update CASE1 set OPENDATE=? where CASENO=?", (od1.get(), i[0][0],))
        cursor.execute("Update CASE1 set CLOSEDATE=? where CASENO=?", (cd1.get(), i[0][0],))
        cursor.execute("Update CASE2 set POLICEID=? where CASENO=?", (pi1.get(), i1[0][0],))
        cursor.execute("Update CASE3 set VFNAME=? where CASENO=?", (victim1.get(), i2[0][0],))
        cursor.execute("Update CASE3 set VMNAME=? where CASENO=?", (victim2.get(), i[0][0],))
        cursor.execute("Update CASE3 set VLNAME=? where CASENO=?", (victim3.get(), i[0][0],))
        cursor.execute("Update CASE3 set VAGE=? where CASENO=?", (age1.get(), i2[0][0],))
        cursor.execute("Update CASE3 set VADDRESS=? where CASENO=?", (address1.get(), i2[0][0],))
        cursor.execute("Update CASE4 set FIRNO=? where CASENO=?", (fr1.get(), i3[0][0],))
        connection.commit()
        tkinter.messagebox.showinfo('TITLE','CASE UPDATED')

    ci = StringVar(t)
    frn = StringVar(t)
    pss = StringVar(t)
    des = StringVar(t)
    o = StringVar(t)
    c = StringVar(t)
    vn = StringVar(t)
    vn1 = StringVar(t)
    vn2 = StringVar(t)
    ag = StringVar(t)
    pii = StringVar(t)
    pnoo = StringVar(t)
    snn = StringVar(t)
    addre= StringVar(t)

    def delete():
        cursor.execute('DELETE from CASE1 where CASENO=?', (i[0][0],))
        connection.commit()
        cursor.execute('DELETE from CASE2 where CASENO=?', (i1[0][0],))
        connection.commit()
        cursor.execute('DELETE from CASE2 where CASENO=?', (i2[0][0],))
        connection.commit()
        cursor.execute('DELETE from CASE4 where CASENO=?', (i3[0][0],))
        connection.commit()
        tkinter.messagebox.showinfo('TITLE','CASE DELETED')
        return

    victim=Label(t, text='Name of victim',font=tkFont.Font(family="Times New Roman", size=16), borderwidth=2, relief="solid",width=15,height=2)
    od=Label(t, text='OPENING DATE',font=tkFont.Font(family="Times New Roman", size=16), borderwidth=2, relief="solid",width=15,height=2)
    address=Label(t, text='ADDRESS',font=tkFont.Font(family="Times New Roman", size=16), borderwidth=2, relief="solid",width=15,height=2)
    victim1 = Entry(t,font=tkFont.Font(family="Times New Roman", size=30),textvariable=vn, borderwidth=2, relief="solid", width = 10)
    victim2 = Entry(t, font=tkFont.Font(family="Times New Roman", size=30), textvariable=vn1, borderwidth=2, relief="solid", width = 10)
    victim3 = Entry(t, font=tkFont.Font(family="Times New Roman", size=30), textvariable=vn2, borderwidth=2,relief="solid", width = 10)
    od1=Entry(t,font=tkFont.Font(family="Times New Roman", size=30),textvariable=o, borderwidth=2, relief="solid")
    address1=Entry(t,font=tkFont.Font(family="Times New Roman", size=30), textvariable=addre, relief="solid")
    case_id=Label(t, text='CASE ID',font=tkFont.Font(family="Times New Roman", size=16), borderwidth=2, relief="solid",width=15,height=2)
    status=Label(t, text='COMPLAINT ID',font=tkFont.Font(family="Times New Roman", size=16), borderwidth=2, relief="solid",width=15,height=2)
    case_id1=Entry(t,font=tkFont.Font(family="Times New Roman", size=30),textvariable=ci, borderwidth=2, relief="solid")
    status1=Label(t, text=i[0][7], borderwidth=2, relief="solid", width=30,height=3)
    desc=Label(t, text='DESCRIPTION',font=tkFont.Font(family="Times New Roman", size=16), borderwidth=2, relief="solid",width=15,height=2)
    desc1=Entry(t,font=tkFont.Font(family="Times New Roman", size=30),textvariable=des, borderwidth=2, relief="solid")
    cd=Label(t, text='CLOSING DATE',font=tkFont.Font(family="Times New Roman", size=16), borderwidth=2, relief="solid",width=15,height=2)
    cd1=Entry(t,font=tkFont.Font(family="Times New Roman", size=30), textvariable=c,borderwidth=2, relief="solid")
    fr = Label(t, text='FIR NUMBER',font=tkFont.Font(family="Times New Roman", size=16), borderwidth=2, relief="solid",width=15,height=2)
    fr1 = Entry(t, font=tkFont.Font(family="Times New Roman", size=30), textvariable=frn, borderwidth=2, relief="solid")
    pi = Label(t, text='POLICE ID',font=tkFont.Font(family="Times New Roman", size=16), borderwidth=2, relief="solid",width=15,height=2)
    pi1 = Entry(t, font=tkFont.Font(family="Times New Roman", size=30), textvariable=pii, borderwidth=2, relief="solid")
    sn = Label(t, text='SECTION NUMBER',font=tkFont.Font(family="Times New Roman", size=16), borderwidth=2, relief="solid",width=15,height=2)
    sn1 = Entry(t, font=tkFont.Font(family="Times New Roman", size=30), textvariable=snn, borderwidth=2,relief="solid")
    back_button = Button(t, text='Go Back',font=tkFont.Font(family="Times New Roman", size=16), command=back, borderwidth=2, relief="solid", width=32, height=2).place(x=1100, y=700)
    ps=Label(t, text='POLICE STATION',font=tkFont.Font(family="Times New Roman", size=16), borderwidth=2, relief="solid",width=15,height=2)
    ps1=Entry(t,font=tkFont.Font(family="Times New Roman", size=30),textvariable=pss , borderwidth=2, relief="solid")
    age=Label(t, text='AGE',font=tkFont.Font(family="Times New Roman", size=16), borderwidth=2, relief="solid",width=15,height=2)
    age1=Entry(t,font=tkFont.Font(family="Times New Roman", size=30),textvariable=ag, borderwidth=2, relief="solid")
    delete=Button(t, text='DELETE',font=tkFont.Font(family="Times New Roman", size=16),command=delete, borderwidth=2, relief="solid",width=15,height=2)
    submit = Button(t, text='SUBMIT',font=tkFont.Font(family="Times New Roman", size=16), command=update_case, borderwidth=2, relief="solid",width=15,height=2)

    victim.place(x=50, y=480)
    age.place(x=50, y=155)
    address.place(x=50, y=220)
    victim1.place(x=300, y=480)
    victim2.place(x=550, y=480)
    victim3.place(x=800, y=480)
    age1.place(x=300, y=155)
    address1.place(x=300, y=220)
    case_id.place(x=50, y=90)
    fr.place(x=50, y=415)
    fr1.place(x=300, y=415)
    case_id1.place(x=300, y=90)
    pi.place(x=850, y=95)
    pi1.place(x=1100, y=95)
    status.place(x=850, y=220)
    status1.place(x=1100, y=220)
    sn.place(x=50, y=610)
    sn1.place(x=300, y=610)
    desc.place(x=50, y=545)
    desc1.place(x=300, y=545)
    ps.place(x=850, y=155)
    ps1.place(x=1100, y=155)
    od.place(x=50, y=285)
    od1.place(x=300, y=285)
    cd.place(x=50, y=350)
    cd1.place(x=300, y=350)
    submit.place(x=1300, y=600)
    delete.place(x=1100,y=600)
    ci.set(i[0][0])
    pss.set(i[0][3])
    des.set(i[0][4])
    o.set(i[0][5])
    c.set(i[0][6])
    vn.set(i2[0][1])
    vn1.set(i2[0][2])
    vn2.set(i2[0][3])
    ag.set(i2[0][4])
    frn.set(i3[0][1])
    pnoo.set(i[0][1])
    pii.set(i1[0][1])
    addre.set(i2[0][5])
    snn.set(i[0][2])
    mainloop()
